// Regenerates the Worker atlas from the curated self-hosted animated emoji set.
// Every atlas option must have a matching public/emoji/*.webp asset.
// Run: npm run build:atlas

import { existsSync, readFileSync, writeFileSync } from "node:fs";

const SOURCE = "scripts/animated-emoji.json";
const ASSET_DIR = "public/emoji";
const MIN_OPTIONS = 256;
const SKIN_TONE_RE = /[\u{1f3fb}-\u{1f3ff}]/u;
const ZWJ_RE = /\u200d/u;
const VARIATION_SELECTOR_RE = /\ufe0f/g;

function visualKey(symbol) {
  return symbol.normalize("NFKC").replace(VARIATION_SELECTOR_RE, "");
}

const entries = JSON.parse(readFileSync(SOURCE, "utf8"));
if (!Array.isArray(entries)) throw new Error(`${SOURCE} must contain an array`);
if (entries.length < MIN_OPTIONS) throw new Error(`expected at least ${MIN_OPTIONS} animated emoji, got ${entries.length}`);

const atlas = [];
const seenSymbols = new Set();
const seenVisuals = new Set();
const seenCodes = new Set();

for (const entry of entries) {
  if (!entry || typeof entry !== "object") throw new Error("bad animated emoji entry");
  const symbol = String(entry.symbol || "");
  const code = String(entry.code || "").toLowerCase();
  if (!symbol) throw new Error("animated emoji entry is missing symbol");
  if (!/^[0-9a-f]+(?:_[0-9a-f]+)*$/.test(code)) throw new Error(`bad animated emoji code for ${symbol}: ${code}`);
  if (SKIN_TONE_RE.test(symbol)) throw new Error(`skin-tone modifier is not allowed: ${symbol}`);
  if (ZWJ_RE.test(symbol)) throw new Error(`ZWJ sequence is not allowed: ${symbol}`);
  const key = visualKey(symbol);
  if (seenSymbols.has(symbol)) throw new Error(`duplicate animated emoji symbol: ${symbol}`);
  if (seenVisuals.has(key)) throw new Error(`visually duplicate animated emoji symbol: ${symbol}`);
  if (seenCodes.has(code)) throw new Error(`duplicate animated emoji code: ${code}`);
  const asset = `/emoji/${code}.webp`;
  if (!existsSync(`${ASSET_DIR}/${code}.webp`)) throw new Error(`missing animated emoji asset: ${ASSET_DIR}/${code}.webp`);
  seenSymbols.add(symbol);
  seenVisuals.add(key);
  seenCodes.add(code);
  atlas.push({ id: atlas.length + 1, symbol, asset });
}

const out =
  "// AUTO-GENERATED by scripts/build-atlas.mjs - do not edit by hand.\n" +
  "export type AtlasEntry = { id: number; symbol: string; asset: string };\n" +
  "export const ATLAS: AtlasEntry[] = " +
  JSON.stringify(atlas) +
  ";\n";

writeFileSync("worker/atlas.ts", out);
console.log("wrote animated atlas:", atlas.length, "self-hosted symbols");
