// Regenerates the 1024-symbol atlas embedded in the Worker.
// The source list is pinned to display-safe RGI emoji from Unicode emoji-test
// 15.1, excluding flags, ZWJ sequences and skin-tone modifiers.
// Run: npm run build:atlas

import { readFileSync, writeFileSync } from "node:fs";

const SOURCE = "scripts/emoji-safe-symbols.json";
const EXPECTED = 1024;
const SKIN_TONE_RE = /[\u{1f3fb}-\u{1f3ff}]/u;
const ZWJ_RE = /\u200d/u;
const VARIATION_SELECTOR_RE = /\ufe0f/g;

function visualKey(symbol) {
  return symbol.normalize("NFKC").replace(VARIATION_SELECTOR_RE, "");
}

const glyphs = JSON.parse(readFileSync(SOURCE, "utf8"));
if (!Array.isArray(glyphs)) throw new Error(`${SOURCE} must contain an array`);
if (glyphs.length !== EXPECTED) throw new Error(`expected ${EXPECTED}, got ${glyphs.length}`);

const seenSymbols = new Set();
const seenVisuals = new Set();
for (const symbol of glyphs) {
  if (typeof symbol !== "string" || symbol.length === 0) throw new Error("bad emoji symbol in source");
  if (seenSymbols.has(symbol)) throw new Error(`duplicate emoji symbol: ${symbol}`);
  if (SKIN_TONE_RE.test(symbol)) throw new Error(`skin-tone modifier is not allowed as an atlas option: ${symbol}`);
  if (ZWJ_RE.test(symbol)) throw new Error(`ZWJ sequence is not allowed as an atlas option: ${symbol}`);
  const key = visualKey(symbol);
  if (seenVisuals.has(key)) throw new Error(`visually duplicate emoji symbol: ${symbol}`);
  seenSymbols.add(symbol);
  seenVisuals.add(key);
}

const atlas = glyphs.map((symbol, i) => ({ id: i + 1, symbol }));
const out =
  "// AUTO-GENERATED by scripts/build-atlas.mjs - do not edit by hand.\n" +
  "export type AtlasEntry = { id: number; symbol: string };\n" +
  "export const ATLAS: AtlasEntry[] = " +
  JSON.stringify(atlas) +
  ";\n";

writeFileSync("worker/atlas.ts", out);
console.log("wrote atlas:", atlas.length, "safe symbols");
